language: python

python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv sync --dev

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
  - PIPENV_DONT_USE_PYENV=TRUE

script: pytest