language: python
dist: xenial
python:
  - "3.7.1"

install:
  - pip install pipenv
  - pipenv install --dev

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: pipenv run pytest