language: python

python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

script: pipenv run pytest